Setup RabbitMQ with docker compose
CMLTeam/cmltemplate pull request #45
Opened 2021-02-22 15:39 UTC by vadymtomashchuk18

2021-02-23 14:52 UTC, xonixx requested changes

2021-02-23 14:52 UTC, xonixx commented on README.md
> +docker network create rabbitmq-cluster
Is this line required? It's not quite clear why we need to setup network for multiple containers if we only run one container.

2021-02-23 14:52 UTC, xonixx commented on src/main/resources/application.yml
> +    allow-bean-definition-overriding: true
Why do we need this setting for configuting RabbitMQ?

2021-02-23 14:52 UTC, xonixx commented on README.md
> +And listener will return to you this message: `Message read from the queue : Prepared message`
Does the docker image include some admin UI for RabbitMQ? If yes - could we please document how to access it?

2021-02-23 14:52 UTC, xonixx commented on README.md
> +docker-compose -f docker-compose-rabbitmq.yml up
Could you please also add a shortcut to this command to `Makesurefile` the same as it's done for mysql/postgre?

The idea here to enable running this just with `./makesure rabbitmq`

2021-02-26 00:33 UTC, vadymtomashchuk18 commented on README.md
> +docker-compose -f docker-compose-rabbitmq.yml up
Done

2021-02-26 17:50 UTC, merged