Spring security
CMLTeam/cmltemplate pull request #47
Opened 2021-05-19 09:44 UTC by IhorTarkhan

2021-05-19 18:59 UTC, xonixx requested changes
I suggest not to over-complicate things now by splitting to multiple modules. To me, it's not realy obvious what separation should be applied and why we need 3 modules, not 2 or 7. Besides, this imposes unneeded mental pressure during developement. Now each time dev adds new class - need to think hard what module should it belong.

Also I suggest to stick to domain-driven design. Thus I propose to approach this in very simle and somewhat dumb way. We should create a single package `security` in existing app and put all new classes in there in flat fashion (despite their role). As an example to this approach please take a look for example at these projects (https://github.com/xonixx/video-reply-telegram-bot2/tree/master/src/main/java/com/cmlteam/video_reply_telegram_bot2 or https://github.com/xonixx/serv/tree/master/src/main/java/com/cmlteam/serv). Overall the idea is that you should organize packages by application domain, not by role (service, controller, repository) and not create superfluous packages.

More arguments against current modules separation:

- I prefer not to mix adding new functionality (the discussed security function) with re-structuring(refactoring) the app. The latter can be done later in separate task if needed.
- **With this change the `init.sh` script functionality most likely is broken**
- More modules complicate (and probably slows down) the building process (mvn)
- The ideas in https://martinfowler.com/bliki/MicroservicePremium.html

Further steps (will be done in separate task(s)):

- Email confirmation via email
- Forgot password
- User management API (list user, add/remove user, set role)
- Basic UI (React or Vue?)

Let's track the progress on this Epic under task https://github.com/CMLTeam/cmltemplate/issues/5

2021-05-19 18:59 UTC, xonixx commented on application/src/main/java/com/cmlteam/cmltemplate/controller/CustomerAuthenticationControllerTest.http
> +  "email": "email333",
Missing email validation

2021-05-19 18:59 UTC, xonixx commented on security/src/main/java/com/cmlteam/cmltemplate/entities/SecurityCustomer.java
> +public class SecurityCustomer extends Customer implements UserDetails {
I don't see a reason why you have 2 @Entity classes SecurityCustomer and Customer. Even more - couldn't this be a single class?

2021-05-19 18:59 UTC, xonixx commented on security/src/main/java/com/cmlteam/cmltemplate/entities/SecurityCustomer.java
> +  // TODO remove mock function
shell we please address all TODOs before merge?

2021-05-19 18:59 UTC, xonixx commented on security/src/main/java/com/cmlteam/cmltemplate/property/JwtProperty.java
> +  @Value("${jwt.secret}")
please change to constructor-based injection

2021-05-19 18:59 UTC, xonixx commented on security/src/main/java/com/cmlteam/cmltemplate/service/SecurityCustomerFilter.java
> +    String jwtLong = request.getHeader("Customer-Authentication-Long");
I don't get why do you use some custome headers (2 of them) instead of using pretty standard Authorization + Bearer scheme (like described in https://www.toptal.com/java/rest-security-with-jwt-spring-security-and-java)

2021-05-19 18:59 UTC, xonixx commented on core/src/main/java/com/cmlteam/cmltemplate/entities/Customer.java
> +public class Customer {
I propose `Customer` -> `User` naming instead

2021-05-19 18:59 UTC, xonixx commented on core/src/main/java/com/cmlteam/cmltemplate/entities/Customer.java
> +  private String lastName;
Customer is missing `role` field in DB. I propose make role configurable on User level and add 2 roles for start: USER and ADMIN. Also add a fixture or migration to add admin user by default to DB.

2021-05-21 16:48 UTC, xonixx requested changes

2021-05-21 16:48 UTC, xonixx commented on src/main/java/com/cmlteam/cmltemplate/controllers/CustomerAuthenticationController.java
> +public class CustomerAuthenticationController {
Let's use `User` terminology in all places vs `Customer` please

2021-05-21 16:48 UTC, xonixx commented on src/main/java/com/cmlteam/cmltemplate/controllers/CustomerAuthenticationController.java
> +  @PostMapping("change-password/{id}/{password}")
It doesn't feel right that password is passed as part of URL. It should go in POST body (JSON)

2021-05-21 16:48 UTC, xonixx commented on src/main/java/com/cmlteam/cmltemplate/controllers/CustomerAuthenticationController.java
> +  @PreAuthorize("hasRole('USER')")
Does it make sense that this method is only allowed for USER role, not ADMIN?

2021-05-21 16:48 UTC, xonixx commented on src/main/java/com/cmlteam/cmltemplate/controllers/CustomerAuthenticationControllerTest.http
> +POST http://localhost:8080/sign-up
I'd prefer that all auth-related actions should sit under some prefix, like `/auth/sign-up`, `/auth/confirm-email/..` etc.

2021-05-21 16:48 UTC, xonixx commented on src/main/java/com/cmlteam/cmltemplate/controllers/CustomerAuthenticationController.java
> +  public void confirmEmail(@PathVariable Long id) {
There is a security problem with this approach. The confirmation URL should not contain predictable parts (like ID which is auto-incremental). Possible correct example of implementation of this is in https://gitlab.com/cml-team/renext/-/blob/master/backend/src/main/java/com/cmlteam/rem/controllers/AuthenticationController.java#L83

2021-05-21 16:48 UTC, xonixx commented on src/main/java/com/cmlteam/cmltemplate/controllers/CustomerAuthenticationController.java
> +  public void confirmEmail(@PathVariable Long id) {
Also this probably should be GET not POST

2021-05-21 16:48 UTC, xonixx commented on src/main/java/com/cmlteam/cmltemplate/controllers/CustomerAuthenticationController.java
> +public class CustomerAuthenticationController {
Also let's not forget please to add all relevant Swagger (OpenAPI) annotations for controllers, actions, models. Since we have Swegger set up by defalt.

2021-05-21 16:48 UTC, xonixx commented on src/main/java/com/cmlteam/cmltemplate/model/request/AuthenticationRequest.java
> +public class AuthenticationRequest {
I still suggest putting ALL classes (even models, repositories, services, etc.) under `security` package, such that all be in one place, not scattered through many packages.

2021-05-21 16:48 UTC, xonixx commented on src/main/java/com/cmlteam/cmltemplate/entities/User.java
> +  private Boolean emailVerified = false;
why not `boolean`?

2021-05-21 16:48 UTC, xonixx commented on src/main/java/com/cmlteam/cmltemplate/security/SecurityConfig.java
> +  @ConditionalOnProperty("jwt.enabled")
Do we still need this line if the same line is present on a class level?

2021-05-21 16:48 UTC, xonixx commented on src/main/java/com/cmlteam/cmltemplate/controllers/CustomerAuthenticationController.java
> +  @PostMapping("change-password/{id}/{password}")
I don't see any security check here. Does it mean that any user can change password for other user?

I think the correct logic is: USER can change only own password, ADMIN can change any password.

2021-05-22 12:34 UTC, IhorTarkhan commented on src/main/java/com/cmlteam/cmltemplate/controllers/CustomerAuthenticationController.java
> +  @PostMapping("change-password/{id}/{password}")
this is only demo how to use security service. I really do not want implement logic like "only ADMIN can change USER password" - because it is can be there no ADMIN role in project.

I absolutely agree that `CustomerAuthenticationController.java` is not security and I add this only as a example. So, you write so many comments for this file, let me just remove 'CustomerAuthenticationController.java' file at all (I will repeat myself: There are no business logic in this file)

2021-05-22 12:35 UTC, IhorTarkhan commented on src/main/java/com/cmlteam/cmltemplate/controllers/CustomerAuthenticationController.java
> +  public void confirmEmail(@PathVariable Long id) {
the same as here https://github.com/CMLTeam/cmltemplate/pull/47#discussion_r637398763

2021-05-22 12:35 UTC, IhorTarkhan commented on src/main/java/com/cmlteam/cmltemplate/controllers/CustomerAuthenticationControllerTest.http
> +POST http://localhost:8080/sign-up
the same as here https://github.com/CMLTeam/cmltemplate/pull/47#discussion_r637398763

2021-05-22 12:35 UTC, IhorTarkhan commented on src/main/java/com/cmlteam/cmltemplate/controllers/CustomerAuthenticationController.java
> +  @PreAuthorize("hasRole('USER')")
the same as here https://github.com/CMLTeam/cmltemplate/pull/47#discussion_r637398763

2021-05-22 12:35 UTC, IhorTarkhan commented on src/main/java/com/cmlteam/cmltemplate/controllers/CustomerAuthenticationController.java
> +  @PostMapping("change-password/{id}/{password}")
the same as here #47 (comment)

2021-05-22 12:37 UTC, IhorTarkhan commented on src/main/java/com/cmlteam/cmltemplate/security/SecurityConfig.java
> +  @ConditionalOnProperty("jwt.enabled")
agree, thanks

2021-05-22 12:37 UTC, IhorTarkhan commented on src/main/java/com/cmlteam/cmltemplate/entities/User.java
> +  private Boolean emailVerified = false;
agree, thanks

2021-05-22 12:38 UTC, IhorTarkhan commented on src/main/java/com/cmlteam/cmltemplate/model/request/AuthenticationRequest.java
> +public class AuthenticationRequest {
agree, thanks

2021-05-24 22:41 UTC, xonixx approved these changes

2021-05-24 22:43 UTC, merged